version: "3.8"

services:
  web:
    build: .
    environment:
      DATABASE_HOST: database
      DATABASE_USER: postgres
      DATABASE_PASSWORD_FILE: /run/secrets/db_password
      DATABASE_DBNAME: rust-charge
      RUST_CHARGE_SESSION_SECRET_FILE: /run/secrets/session_secret
      RUST_CHARGE_PUSHOVER_API_TOKEN_FILE: /run/secrets/pushover_api_token
      RUST_CHARGE_PUSHOVER_USER_KEY_FILE: /run/secrets/pushover_user_key
      RUST_CHARGE_LOG: rust_charge=info
    depends_on:
      database:
        condition: service_healthy
    secrets:
      - db_password
      - session_secret
      - pushover_api_token
      - pushover_user_key
    restart: unless-stopped

  database:
    image: "postgres:14-bookworm"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: rust-charge
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "--timeout",
          "0",
          "--dbname",
          "rust-charge",
          "--username",
          "postgres",
        ]
      interval: 5s
      timeout: 3s
      retries: 1
    secrets:
      - db_password
    restart: unless-stopped

volumes:
  postgres-data:
